### ISSUE TITLE
"You don't have permission to view this directory or page."

### ISSUE THREAD

**Issue by jamiecooper** [davidebbo/davidebbo.github.io#24]
David,
Not to sound redundant, but I deployed my program to Azure using Github per a video you created. Now when I open the website in a browser, it gives me an error saying, "You don't have permission to view this directory or page." Can you send me a link on how to fix this? 
Thanks,
Jamie

**Comment by davidebbo** [comment]
Hi Jamie,

This repo is only for comments about my blog post. For Azure Websites questions, please use the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) instead. Thanks!
