### ISSUE TITLE
ArgumentException when the view contains Html.AntiForgeryToken()

### ISSUE THREAD

**Issue by moshfegh** [davidebbo/davidebbo.github.io#25]
Hi David, 

First, thanks for your SUPER AWESOME framework for testing MVC views. I absolutely love it! 

I just have an issue, which was reported 3 years ago but appears in a different way now. I get an ArgumentException when the view contains Html.AntiForgetyToken()

An HttpContext is required to perform this operation. Check that this operation is being performed during a web request.

Previously, the errors others reported involved something to do with HttpCookies. I'm aware that you changed the source code to address that issue. But the exception I get is of type ArgumentException().

Could you please help me resolve this? I'm in the middle of something and desperately need to get this fixed!! Thanks David :)

**Comment by davidebbo** [comment]
This place is most to report issues about the blog itself. Can you repost the issue on the relevant Project (and I'm not sure what project you're referring to here, maybe RazorGenerator?).

**Comment by moshfegh** [comment]
Hi David! Yes it was about RazorGenerator. I'll repost the question there. I'd really appreciate if you help me out with this issue because I really like your framework but this issue is preventing me from using it to its fullest potential.

**Comment by davidebbo** [comment]
Thanks! BTW, on an OSS project issue board, please avoid addressing an issue directly to one person, as it discourages responses from others. There are other contributors :)
