### ISSUE TITLE
Nuget as a Protocol  

### ISSUE THREAD

**Issue by cgatian** [davidebbo/davidebbo.github.io#27]
David,

Let me start off by saying, thank you for your time and work on Nuget. I've spent the majority of the week digging through the source and blogs referencing the framework, and I am truely excited to see its extensibility.

I am attempting to use nuget.core to retrieve packages from a private server and install them.  These packages are considered "update packs" and will replace dlls/content within a running application.  I was able to successfully create packages, serve them, and create a package retrieval application.  However, I was stuck wondering if Nuget has the mechanisms to perform the proper file copies?  I'm pretty sure once you download a package it's then in the developer's hands to properly extract the package appropriately.  The magic that happens in visual studio is due to leveraging the existing functionality to add/remove files and references within the MSBuildProjectSystem class.

Are my findings correct?  Or did I miss a piece of functionality within one of the libraries that will allow me to update dlls/content on a target folder.

**Comment by davidebbo** [comment]
Thanks for contacting me. This issue tracker is mostly to report issues with my blog. For NuGet discussions, the best place to go is https://github.com/nuget/home. I no longer work on the NuGet team, so I'm not as involved as I used to be, but there are lots of experts over there! :)
