### ISSUE TITLE
Using Kudu to change virtual directory physical path

### ISSUE THREAD

**Issue by davideweaver** [davidebbo/davidebbo.github.io#28]
Hi David. I'm trying to change the physical path of my webroot to a folder under "wwwroot". Using Kudu and deploy.cmd, I am launching a powershell script and using Microsoft.Web.Administration.ServerManager to do it, but I get a permission error when I do CommitChanges(). Can I launch the powershell script under elevated permissions or is there a better way to do what I want?

Thanks!
Dave Weaver

**Comment by davidebbo** [comment]
Thanks for contacting me. This issue tracker is mostly to report issues with my blog. Can you post to https://github.com/projectkudu/kudu instead? Thanks!

**Comment by davidebbo** [comment]
And please specify whether you see this when running Kudu on Azure Web Apps or on your own Kudu installation.
