### ISSUE TITLE
Build 2015 Scripts

### ISSUE THREAD

**Issue by Soopster** [davidebbo/davidebbo.github.io#29]
Hi David,
Enjoyed your build talk. Are you able to share your Resource manager templates and Powershell scripts you used in your demos?

Thanks

**Comment by davidebbo** [comment]
Glad you liked the talk!

- ARMClient tool I was using: http://blog.davidebbo.com/2015/01/azure-resource-manager-client.html
- Resource Explorer site: https://resources.azure.com/
- The simple template is here: https://github.com/davidebbo/AzureWebsitesSamples/blob/master/ARMTemplates/EmptyWebApp.json
- The big templates, along with the matching app, are here: https://github.com/davidebbo-test/ToDoApp/tree/master/ARMTemplates

And the few PowerShell commands I used:

```
Switch-AzureMode -Name AzureResourceManager
Add-AzureAccount

New-AzureResourceGroup -Name DemoResourceGroup -Location "West US" -TemplateFile EmptyWebApp.json -siteName DemoSite12345
New-AzureResourceGroup -Name ToDoAppDemoDev -Location "West US" -TemplateFile Dev.json -hostingPlanName ToDoAppDemoDev -siteName ToDoAppDemoDev -siteLocation "West US" -repoUrl "https://github.com/davidebbo-test/ToDoApp" -branch dev -sqlServerName todoappdemodev-server -sqlServerAdminLogin davidebbo -Force
New-AzureResourceGroup -Name ToDoAppDemo -Location "West US" -TemplateFile ProdAndStage.json -hostingPlanName ToDoAppDemo -siteName ToDoAppDemo -siteLocation "West US" -repoUrl "https://github.com/davidebbo-test/ToDoApp" -branch master -sqlServerName todoappdemo-server -sqlServerAdminLogin davidebbo -Force
```

Let me know if I'm missing anything you need!

**Comment by Soopster** [comment]
Great,
Thanks very much
