### ISSUE TITLE
Different behavior on Get-AzureResource

### ISSUE THREAD

**Issue by alexwcy** [davidebbo/davidebbo.github.io#32]
Hi David, I have one powershell script which working fine in V0.9.0. Example: $resource = Get-AzureResource -Name $name -ResourceGroupName $resourceGroup -ResourceType $resourceType -ApiVersion $apiVersion -ErrorAction SilentlyContinue.

The purpose of this script is to check whether the resource exists or not. If exists then i will skip to call New-AzureResource else will create new azure resource.

After i upgraded to the latest version of Azure Powershell like V0.9.1 and also the latest V0.9.3, the above command will throw exception if not exists. Exception:

```
Get-AzureResource : {

"Error": {

"Code": "ResourceNotFound",

"Message": "Resource not found.",

"Target": null,

"Details": null

}

}

At line:1 char:1

+ Get-AzureResource -Name "websiteName" -ResourceGroupName ResGrp -Res ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : CloseError: (:) [Get-AzureResource], ErrorResponseMessageException

+ FullyQualifiedErrorId : ResourceNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
```

I expect the behavior in V0.9.0 which return null so that i can do the checking.

Any idea?

Thanks in advance.

**Comment by davidebbo** [comment]
Not sure. I will ask the team that owns this whether they changed the behavior.

**Comment by davidebbo** [comment]
Actually, it would be best to post this directly where the team can see it, which is on [this forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=azurescripting). Let me know the link once you have posted. Thanks!

**Comment by alexwcy** [comment]
Hi David, sorry for posted my question in wrong place. I just re-posted in the forum that you mentioned. Here is the link https://social.msdn.microsoft.com/Forums/azure/en-US/cf5f7777-e5f2-4423-bdcd-db4b611e1be6/different-behavior-on-getazureresource-it-started-to-throw-resourcenotfound-exception-from-v091?forum=azurescripting

Hope the related team can look into this issue and get back to us as soon as possible.

**Comment by davidebbo** [comment]
I pointed a couple people to your thread. Though they seem to be out of the office for a few days, so not sure when they'll respond.

As an aside, the ARM way is that PUTs are idempotent, so in theory you should not need to check existence before doing the PUT.
