### ISSUE TITLE
Razor Generator support mvc 6

### ISSUE THREAD

**Issue by quantruong** [davidebbo/davidebbo.github.io#35]
Hi David,

Can you tell me Razor Generator support mvc 6? If yes, How can to do that , because I don't see Custom Tool when view properties cshtml view. If no, Can you provide me suggestion to do that? , I will  research it.

Thanks,
Quan

**Comment by davidebbo** [comment]
Hi Quan,

Please use https://github.com/RazorGenerator/RazorGenerator for all Razor Generator related discussions. Thanks!

David
