### ISSUE TITLE
Kudu Project

### ISSUE THREAD

**Issue by ryanande** [davidebbo/davidebbo.github.io#36]
Hey David,

I have given a few presentations on the Kudu project over the past 8 months locally.
Next week I am presenting @ KCDC (http://www.kcdc.info/#!/speakers/ryan-anderson).

I was wondering, is there anything new on the horizon or any particular area of the feature set that could use a little more attention in relation to others. As VS2015 and all the new love from you guys at MS is getting ready to drop there are some enormous changes coming.

In light of that, was just fishing to see if there might be anything more contemporary on the Kudu front that would be worth focusing on.

Many thanks for your time, and love what you guys are doing!

Sincerely,
Ryan Anderson

**Comment by davidebbo** [comment]
Hey Ryan,

Biggest new recent thing in Kudu is probably the support for scheduled jobs without having to involve the Azure scheduler ([blog post](http://blog.amitapple.com/post/2015/06/scheduling-azure-webjobs/)).

Also, ASP.NET 5 beta 4 support, and preliminary support for Go. See https://github.com/projectkudu/kudu/wiki/Version-history.

Good luck with the talk!
David

**Comment by ryanande** [comment]
Many thanks David!
