### ISSUE TITLE
t4mvc issue

### ISSUE THREAD

**Issue by yeganehaym** [davidebbo/davidebbo.github.io#37]
hi sir
i have a problem with t4mvc and i think it's a bug
please check it out
https://github.com/T4MVC/T4MVC/issues/36#issuecomment-116501880
thanks

**Comment by davidebbo** [comment]
Looks like it was already solved by @kevinkuszyk. Closing here to keep discussion there. Please comment on that issue if his suggestion did not work.

**Comment by yeganehaym** [comment]
no
it didn't solved if you read it
he told use action result not my custom action result
its' like dont write app if you have problem in your app
like microsoft has problem in windows and users cant install it
so microsoft dont write windows anymore

**Comment by davidebbo** [comment]
You misread his answer. What he suggested should work, but let's take the discussion there. I saw your reply there, and it does not make it clear what you try. Please avoid rants in your replies, as that rarely helps :)

**Comment by yeganehaym** [comment]
ok
thanks
sorry
because he closed topic there and i think he said i should write my code in controller instead of custom action result and it was unlogical for me and i didnt know it means is return type and i was sad
thank you again
