### ISSUE TITLE
Please help us with a info about Azure Websites

### ISSUE THREAD

**Issue by pisoiasul** [davidebbo/davidebbo.github.io#38]
Hello,

I have a bet with a friend, what I told him was that all my azure websites (basic mode) are hosted on a single VM. His opinion was that each website in on a different VM. Can you please solve our dilemma/bet ? 

Thanks

**Comment by davidebbo** [comment]
It comes down to whether they're hosting in the same App Service Plan. See details [here](https://azure.microsoft.com/en-us/documentation/articles/azure-web-sites-web-hosting-plans-in-depth-overview/).

So technically, neither of your statements is correct in the general sense, but can be correct in some situation. You can decide if that means you both win or both lose ;)

**Comment by pisoiasul** [comment]
In the same app service plan, yes.

 

Thanks !
