### ISSUE TITLE
Azure Deployment Recommendations?

### ISSUE THREAD

**Issue by markalanevans** [davidebbo/davidebbo.github.io#39]
Hi David,

I just got done watching this: https://channel9.msdn.com/Events/Speakers/david-ebbo and its awesome.

We are going to move our existing infrastructure from a collocation to Azure App Service.

Coming from the AWS (Ansible, Ruby, Rails migrations, Jenkins, etc) world I'm familiar with deployments, and while the Azure ecosystem looks awesome, I haven't found a solid up-to-date blog post on many of the items you talk about in your video, but that also addresses some standard additional items.
I could really use your help in pointing me towards the best practices and methods to do some pretty standard things during our deployment.

I'm sure you are crazy busy so no offense taken if you can't reply, but if you have a few seconds, below are a few questions for which I'd love your recommendations on.

Thanks in advance.

#### Questions
* In your video above you talk about [ARM](http://blog.davidebbo.com/2015/01/azure-resource-manager-client.html) and templates. Do you have those files for the demo?

### Database Migrations/Updates
We have our own custom exe for database migrations that works similar to how the EF framework "Code First" database migrations work in regards to making database changes.   

##### Questions 
* What is the recommended way to run these during a deployment? 
* How / Where should we put these in our Code/App?
* Can we trigger these to be run on only machine? ( ex if we have 3 instances running we don't want all 3 instances running the migration scripts). 

### Cron Jobs & Manual/Deploy "Scripts"
Currently we have single console app that continually grows with switch cases allowing us to trigger application logic via a cron job or executed manually on our servers.

##### Questions
* Do we need to create separate  WebJobs / in our project for each "Job" 
* For scripts that we need to run manually what is the suggested method? 
* If we need to trigger a script before/during/after a deployment to the database, how & where should we configure this?

Thanks again for the video, it's been really helpful.

-Mark

**Comment by davidebbo** [comment]
Hi Mark,

Take a look at #29, which links to most of the material from my Build talk.

For your other questions, it would be best to start a few separate threads on the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview). This will give it more visibility, and will make it easier to involve others from the team.

thanks!
David

**Comment by markalanevans** [comment]
Thank you for the Assets!

I have created the DB question as you suggested.

### DB Questions:
https://social.msdn.microsoft.com/Forums/azure/en-US/cede7fc0-680a-4da5-8877-b425ee21144b/deployment-best-practice-database-migrations-custom-sql-scripts?forum=windowsazurewebsitespreview

Thanks so much.

-Mark
