### ISSUE TITLE
ToDo Demo - Integrating CI Tool

### ISSUE THREAD

**Issue by markalanevans** [davidebbo/davidebbo.github.io#41]
In your video: https://channel9.msdn.com/Events/Build/2015/2-620

How would a CI Tool like Team City or Jenkins fit into this workflow?

**Comment by davidebbo** [comment]
It could be something that GitHub triggers via a hook before triggering the Azure hook, and set up such that if CI fails it doesn't do the next hook. Note that I have not actually tried that, so I'm not sure exactly how the hook chaining behavior works.

**Comment by fldeploy** [comment]
Ok. I'll check that out.

Thanks so much

**Comment by markalanevans** [comment]
Ok. I'll check that out.

Thanks so much
