### ISSUE TITLE
Azure Website deployment by build server over msdeploy

### ISSUE THREAD

**Issue by OpenSrcDev** [davidebbo/davidebbo.github.io#42]
Dear David

I follow your article about the deployment to azure website, it was very helpfull to set up on build server to create package and deploy. 

I have strange issue , In the azure portal we can configure table storage for logging so that all application trace message come to table storage log. 

When i deploy to over build server then trace messages does not appear to table storage but when i deploy over visual studio publish then trace message come to table storage. 

Could you please help in spotting this issue?

Thanks alot.
Chandra

**Comment by davidebbo** [comment]
Hi Chandra,

Please see https://github.com/davidebbo/davidebbo.github.io/wiki for better place to discuss this.

Thanks!
David
