### ISSUE TITLE
Unit test your MVC views using Razor Generator

### ISSUE THREAD

**Issue by jacksparrow89** [davidebbo/davidebbo.github.io#44]
Hi David, I just wanted to ask if the RazorGenerator, works with MVC 4 and 5 as well ? Because I am having problem in creating unit tests for my Index View in the test project.

As soon as I write var view = new Index(); the compile time error appears saying its a method and used like a class ...
I might be missing some steps to add the unit test for a view.
Please help

**Comment by davidebbo** [comment]
Please use https://github.com/RazorGenerator/RazorGenerator instead for all RG related things. Thanks!
