### ISSUE TITLE
WebApp access denied

### ISSUE THREAD

**Issue by edtheshed** [davidebbo/davidebbo.github.io#46]
Hi David,

I would really appreciate if you could have a look at a question of mine on stackoverflow.

[Question](http://stackoverflow.com/questions/34750600/set-password-access-denied-from-azure-webjob)

It seems to me that a WebApp may not be the way to do this. Should I be using a cloud service with a worker role?

Thanks

Edit: Sorry David, didn't realise this wasn't the place for questions like this. I have since posted this on the msdn forum.

**Comment by davidebbo** [comment]
Sorry, not sure about this one, but hopefully others will have thoughts.
