### ISSUE TITLE
Azure Web HTTP returns 500 error after 230 seconds wait

### ISSUE THREAD

**Issue by nboettcher** [davidebbo/davidebbo.github.io#48]
Hi David,

I am running into an issue with on my web app on Azure calling an web API I am also hosting on Azure. The web app is running a report that could take 4-5 minutes to run and process. However, after 3.8 minutes (230 seconds) we are getting a 500 returned to the web app but the process continues to run on the web API. I found a forum post with the same issue and your response about a year ago. I just wanted to check if this issue still exists and if there is any workaround?

https://social.msdn.microsoft.com/Forums/en-US/17305ddc-07b2-436c-881b-286d1744c98f/503-errors-with-large-pdf-file?forum=windowsazurewebsitespreview

Thanks,
Nate

**Comment by davidebbo** [comment]
Yes, the status in that forum thread is still current. Please follow up there if needed rather than here. This issue tracker is only to discuss issues with blog posts. Thanks!
