### ISSUE TITLE
Azure webjob webhooktrigger issue

### ISSUE THREAD

**Issue by diogoandrei** [davidebbo/davidebbo.github.io#49]
Hi. Sorry to bother you, but I'm attempting to POST to a webjob function with webhooktrigger but I'm getting the error

`An attempt was made to access a socket in a way forbidden by its access permissions`

Do you have any idea why and how I could solve that? Thank you!

**Comment by davidebbo** [comment]
Please use https://github.com/projectkudu/kudu/issues for all Kudu issue. This tracker is only for comments related to my blog. Thanks!
