### ISSUE TITLE
Razor generator with Visual Studio 2015?

### ISSUE THREAD

**Issue by wallace740** [davidebbo/davidebbo.github.io#50]
Hi there

Exciting contribution Razor Generator. 

We needed exactly this extension in our group project, we would like to keep our partial views in another project but we could not make it work with Visual Studio 15, in the properties window there is no Custom tool or we could not find it. is this compatible with Visual Studio 15?

**Comment by davidebbo** [comment]
Wrong place :) Please see https://github.com/davidebbo/davidebbo.github.io/wiki/Purpose-of-the-issue-tracker.
