### ISSUE TITLE
Python Site Extension - Azure x86

### ISSUE THREAD

**Issue by MilosMa** [davidebbo/davidebbo.github.io#51]
Hello David,
I am using Azure and I am just moving our solution into Azure Web App cloud. Our solution is based on Python 3.5.1 x86 and we are using plenty of libraries.
I found and used your Python Extensions (https://github.com/davidebbo/PythonSiteExtension).
If I'm right, this extension install Python 3.5.1 x64.
Do you have it for x86 version also? 

I am struggling with installation of several libraries, i.e. defusedxml, django-rest-auth etc. During installation I am receiving error Command "python setup.py egg_info" failed with error code 1 in D:\local\Temp\pip-build-_2f6gkzp\defusedexpat\ . Detail message in web page is:
Traceback (most recent call last):
  File "D:\home\Python35\wfastcgi.py", line 711, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "D:\home\Python35\wfastcgi.py", line 556, in read_wsgi_handler
    env = get_environment(physical_path)
  File "D:\home\Python35\wfastcgi.py", line 379, in get_environment
    doc = minidom.parse(web_config)
  File "xml\dom\minidom.py", line 1957, in parse
  File "xml\dom\expatbuilder.py", line 32, in <module>
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.

I already read the web from beginning to end and back and because I did not find any solution, I am trying contact you.

Thank you very much for your support and answers.
Answer "I have no idea" or "I dont know" is also appreciated :)

Best Regards

Milos

**Comment by davidebbo** [comment]
Hi Milos,

Would be best to discuss on the extension's repo, or maybe the Azure Web App forum. See https://github.com/davidebbo/davidebbo.github.io/wiki/Purpose-of-the-issue-tracker

thanks,
David
