### ISSUE TITLE
Updating azuredeploy.json for nightscout project

### ISSUE THREAD

**Issue by baembel08** [davidebbo/davidebbo.github.io#52]
Hi dave,
my name is Arndt from Hamburg/Germany.
I'm using Nightscout and noticed that you did provide an azure template for deploying cgm-remote-monitor. I just made more additions with choosable parameters for nearly automatic deploying.
I've tried an update via github, but get errors. the json file is attached. Take a look at it and if its ok, you can make an update ?
greetings from Germany,

Arndt
[azuredeploy.txt](https://github.com/davidebbo/davidebbo.github.io/files/204427/azuredeploy.txt)

**Comment by davidebbo** [comment]
Hi Arndt,

It would be best to discuss directly in the issue tracker from that project, as no one else will see it here (and I'm not associated with the project beside this one small contrib).

thanks!
David
