### ISSUE TITLE
Mocking ControllerContext

### ISSUE THREAD

**Issue by arunln** [davidebbo/davidebbo.github.io#53]
How to mock display mode. As i am getting null reference exception for controller context in my controller class.

[Test.txt](https://github.com/davidebbo/davidebbo.github.io/files/281271/Test.txt)

**Comment by davidebbo** [comment]
Please see https://github.com/davidebbo/davidebbo.github.io/wiki/Purpose-of-the-issue-tracker. Thanks!

**Comment by arunln** [comment]
Ok. Thanks for the update. I will raise queries in concern secion.
