### ISSUE TITLE
NuGet Visual Studios 2012

### ISSUE THREAD

**Issue by RBodnar66** [davidebbo/davidebbo.github.io#54]
Hi,

I'm helping a developer to figure out why NuGet will not launch for VS 2012, but it launches for 2010. When he runs NuGet, he gets a black window. It appears to have launched, but you only have a black screen.

**Comment by davidebbo** [comment]
Wrong place for this :) See https://github.com/davidebbo/davidebbo.github.io/wiki/Purpose-of-the-issue-tracker
