### ISSUE TITLE
No intellisense in javascript (*.js) file when using T4MvcJs

### ISSUE THREAD

**Issue by asadwaheed1984** [davidebbo/davidebbo.github.io#55]
I have started using T4MvcJs in my project recently. The problem I am facing is that, I am unable to use Intellisense feature in my javascript file (.js) when using T4MvcJs (generated strongly-typed) URLs, and I have to type precisely all strongly typed URLs without intellisense. Note that, javascript (.js) file is separately maintained from its razor view file (*.cshtml). This is making the usage of T4MvcJs very difficult.

Please guide, whether intellisense feature is available in T4MvcJs or not? If availble, kindly guide how to enable/use it?

For example: The url in my javascript file w/o using T4MvcJs is declared as

var _url = "/Home/Index"

Kindly guide, how can I write the above url using T4MvcJs in my javascript (*.js) file. Also explain, how to achieve it using intellisense.

Application Plateform: C# + MVC4 , VS 2013

PS: Kindly send me reading resources for T4MvcJs , as I couldn't find much reources on internet.

**Comment by davidebbo** [comment]
Sorry, you have the wrong guy. I own T4MVC, but I'm not familiar with T4MvcJs.

**Comment by asadwaheed1984** [comment]
Please guide who is the right person to contact with for MvcJs? Thanks

**Comment by davidebbo** [comment]
I have no connections to that project, but searching for it, this seems to be its home: https://t4mvcjs.codeplex.com/
