### ISSUE TITLE
Unit Testing Precompiled MVC Views

### ISSUE THREAD

**Issue by alexbernaden** [davidebbo/davidebbo.github.io#57]
In June 2011, you described how precompiling MVC Razor views with RazorGenerator enables unit testing of our views, and promised to cover this topic in more details in a future post. Do you have more information about this testing?

**Comment by davidebbo** [comment]
Please use https://github.com/RazorGenerator/RazorGenerator for all RG related questions. See [here](https://github.com/davidebbo/davidebbo.github.io/wiki/Purpose-of-the-issue-tracker). Thanks!
