### ISSUE TITLE
Get AccessToken for a user using ServicePrincipal

### ISSUE THREAD

**Issue by rajvipatel** [davidebbo/davidebbo.github.io#60]
Hi,

I cam across your informational post regarding the ServicePrincipal and how to use it.
In my project, I am trying to get the access token for a user in my active directory and I need the groups and roles in the access token result. The issue is described in detail here : http://stackoverflow.com/questions/39712989/adal-java-library-for-access-token-not-returning-groups-and-roles

Could I use ServicePrincipal to actually authenticate my user and get the access token with the info of groups and roles ?

**Comment by davidebbo** [comment]
That goes a bit beyond my AAD knowledge :). If you don't get Answer via SO, please try the [AAD Forum](https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=WindowsAzureAD).
