### ISSUE TITLE
Error message adding https://github.com/davidebbo-test/Mvc52Application.git to an ARM template

### ISSUE THREAD

**Issue by svenvanrijen** [davidebbo/davidebbo.github.io#61]
Hi David,

I try to add https://github.com/davidebbo-test/Mvc52Application.git to an ARM template and deploy it to Azure, but I get the error message stated below. Do you have any idea what is going on?

Thanks in advance,

kind regards,
Sven

New-AzureRmResourceGroupDeployment : 18:40:21 - Resource Microsoft.Web/sites/sourcecontrols '0317unicorner-site-3/web' failed with message '{
  "Code": "BadRequest",
  "Message": "Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetWebHookInfo: Not Found\r\n   at Microsoft.Web.Hosting.So
urceControls.GitHubProxy.<ProcessResponse>d__a2`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaite
r.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProx
y.<GetWebHookInfo>d__6f.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task 
task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<AddWebHook>d__36.MoveNe
xt()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.
CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.MoveNex
t().",
  "Target": null,
  "Details": [
    {
      "Message": "Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetWebHookInfo: Not Found\r\n   at Microsoft.Web.Hostin
g.SourceControls.GitHubProxy.<ProcessResponse>d__a2`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAw
aiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHub
Proxy.<GetWebHookInfo>d__6f.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(T
ask task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<AddWebHook>d__36.Mo
veNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runt
ime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.Mov
eNext()."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "Code": "BadRequest",
        "Message": "Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetWebHookInfo: Not Found\r\n   at Microsoft.Web.Host
ing.SourceControls.GitHubProxy.<ProcessResponse>d__a2`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.Task
Awaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitH
ubProxy.<GetWebHookInfo>d__6f.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<AddWebHook>d__36.
MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Ru
ntime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.M
oveNext().",
        "ExtendedCode": "05007",
        "MessageTemplate": "Repository '{0}' operation failed with {1}.",
        "Parameters": [
          "UpdateSiteSourceControl",
          "Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetWebHookInfo: Not Found\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<ProcessResponse>d__a2`1.MoveNext()\r
\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.Compil
erServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<GetWebHookInfo>d__6f.MoveNext()\r\n--- End of stack trace f
rom previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.Han
dleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<AddWebHook>d__36.MoveNext()\r\n--- End of stack trace from previous location where ex
ception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotifi
cation(Task task)\r\n   at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<UpdateSiteSourceControl>d__6.MoveNext()"
        ],
        "InnerErrors": null
      }
    }
  ],
  "Innererror": null
}'

**Comment by davidebbo** [comment]
Not the right place for this :) See [here](https://github.com/davidebbo/davidebbo.github.io/wiki).
