### ISSUE TITLE
looking for ionic2 help

### ISSUE THREAD

**Issue by DigitalBanana** [davidebbo/davidebbo.github.io#62]
Hey David,

Sorry to hit you out of the blue but I am having issues building an ionic2/agular2 app via Kudu in Azure App service. I can serve and build the app locally on my windows 10 box but when i try to run via kudu in app service I see failures with spdx licensing when .stagiing/model_modules...it *seems* to be down to needing to run npm install ionic with the "-g" switch. Can you advise of what I need to do to resolve this (eg do you need more info etc)

sorry and thanks

Dave Lowe

**Comment by davidebbo** [comment]
Hi Dave,

Can you open an issue in https://github.com/projectkudu/kudu instead? Thanks!
