### ISSUE TITLE
Functions app miss behaving after update of functions "framework"

### ISSUE THREAD

**Issue by TonnyMediamonks** [davidebbo/davidebbo.github.io#63]
Hey David,

First, thanks for all the great work.

I don't really know where to turn with my problem, but I know you can at least help me in the right direction.

My problem is with a functions app in a dynamic plan that has been updated via the button on the functions blade. After the update the entire thing fails with a user/pass error. Fortunately it is a dev environment, so I could easily deploy a new env next to it. I left it to figure out what happened when I get time to dig in. I still haven't got the time.

Perhaps you or the functions team may learn a thing or two from it.

Thanks,
Tonny

**Comment by davidebbo** [comment]
Hi Tonny,

Can you please post to the Functions Forum instead? See https://github.com/davidebbo/davidebbo.github.io/wiki. Thanks!

**Comment by TonnyMediamonks** [comment]
Sorry, didn't see that.

I came here from your blog, through the contact link, which pointed me to an issue input page. Perhaps change that to the wiki page first, and a continuation link to the issue input page.

The thank you for the great work still stands!

**Comment by davidebbo** [comment]
I just added an issue template. which explains what the issue tracker is for at the time someone creates an issue. Thanks for the suggestion!
