### ISSUE TITLE
Reset By Peer - Error in Web API hosted in Azure

### ISSUE THREAD

**Issue by nidps** [davidebbo/davidebbo.github.io#64]
Hi David,

I am working on a Service Fabric Web API Project hosted in Azure,and this API is used by our client iOS and Android applications,sometimes we are getting Reset by Peer error(This is what we can see in HTTPScoop) and we wont get the response from API,we didn't find any issues from the service side,as a work around for this we just rebuild and deploy the solution whenever it occurs. Is anyway we can handle this in WebAPI? 

Thanks for your help,
Nidhish.

**Comment by davidebbo** [comment]
Hi Nidhish,

Wrong place for this. Please see https://github.com/davidebbo/davidebbo.github.io/wiki for the purpose of this issue tracker.
