### ISSUE TITLE
link not found

### ISSUE THREAD

**Issue by random-creator** [davidebbo/davidebbo.github.io#67]
Hello,

This url give not found error - http://blog.davidebbo.com/2014/12/azure-service-principal.html)

Thanks!

Please note that this issue tracker is only used to discuss issues with the blog content, e.g.

- RSS feed is not working
- Some UI issue
- Some typos in some of the article
- etc...

For issues relating to other projects, please use the issue in the relevant repo, StackOverflow, MSDN Forum, ...

The reason I want to avoid having technical discussions here is that no one else will find them here, and I prefer having them is a real open forum.

Thanks for reading my blog!

**Comment by davidebbo** [comment]
http://blog.davidebbo.com/2014/12/azure-service-principal.html works fine now. Maybe it was some brief GitHub pages issue.
