### ISSUE TITLE
Inaccurate/outdated information on projectkudu/kudu/wiki/Azure-Web-App-sandbox

### ISSUE THREAD

**Issue by VitaliyMF** [davidebbo/davidebbo.github.io#68]
Hi David,

I'm contacting you because you mentioned as last editor of the following wiki page:

https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

regarding "Unsupported frameworks" section for PDF generators. It states that "NReco (uses wkhtmltopdf)" is not supported, but "Rotativa / wkhtmltopdf: requires the site to run in Basic or higher." is _supported_. With VM-based Azure Apps plans all PDF generators based on wkhtmltopdf will work identically and produce the same results; NReco PdfGenerator wrapper also works fine with Basic plan or higher. 

BTW, one issue with Azure Apps environment still exists (and it affects all PDF generators based on WebKit/Qt like wkhtmltopdf or phantomjs): sandbox doesn't allow to load custom fonts and wkhtmltopdf fallbacks to the one of the system-installed fonts (like Arial).

**Comment by davidebbo** [comment]
@VitaliyMF unfortunately, GitHub doesn't support PRs on wiki repos. But if you paste some replacement markdown for that section in this issue, I can then make the edit. You obviously know more than I do about wkhtmltopdf, so I'll take your word for it :)

**Comment by VitaliyMF** [comment]
@davidebbo as reader I have no access to the wiki representation of this page; could you remove "

> - NReco (uses wkhtmltopdf)

from the list that goes after "PDF generators failing due to restriction mentioned above".

and move it to the list after "The following PDF generators are supported":

> - Rotativa / wkhtmltopdf: requires the site to run in Basic or higher.
> - NReco PdfGenerator (wkhtmltopdf): requires subscription plan Basic or higher

also you can add notice about custom fonts:

> Known issue for all PDF generators based on wkhtmltopdf or phantomjs: custom fonts are not rendered (system-installed font is used instead) because of sandbox GDI API limitations that present even in VM-based Azure Apps plans (Basic or higher).

Thank you in advance! :)

**Comment by davidebbo** [comment]
Done deal, thanks!

**Comment by paraspatidar** [comment]
**********************************************************
**Issue with function app while using NReco** 
***************************************************

As of Current scenario ,  NReco (uses wkhtmltopdf) is supported from Azure Sandbox perspective if the plan is basic and above.
However this works well with Azure _web App_ , but for Azure _Function App_ perspective , there is a tweak.
During object creation of NReco.PdfGenerator.HtmlToPdfConverter(); , it pics some path which is 
"'_D:\Program Files (x86)\SiteExtensions\Functions....."_  of Kudu which reas readonly and thus on function app it fails.

The Trick to make this working is to manually set the path of this object to some writable location , lets say "D:\home\LogFiles"

, thus modifying the code like this will help this work on function app as well.

              var htmlContent = String.Format("<body><h1>Hello world:</h1> {0}</body>", DateTime.Now);
                var htmlToPdf = new NReco.PdfGenerator.HtmlToPdfConverter();
                **htmlToPdf.PdfToolPath** = @"D:\home\LogFiles";
                var pdfBytes = htmlToPdf.GeneratePdf(htmlContent);
                string result = System.Text.Encoding.UTF8.GetString(pdfBytes);

-----------------------------------------------------

**Comment by davidebbo** [comment]
@paraspatidar this is probably not the best place to drill into NReco issues. Can you instead open an issue on https://github.com/nreco/nreco to discuss with @VitaliyMF? Thanks!
