### ISSUE TITLE
Add-BindingRedirect

### ISSUE THREAD

**Issue by zooly57** [davidebbo/davidebbo.github.io#69]
Greetings,

I am trying to use the nuget **Add-BindingRedirect** in a Powershell script I created.  Windows Powershell says the command is not recognized. Ultimately, I want to set this up to run under Jenkins for doing automated builds. Do I need to install something or add something to my path to allow me to access the Powershell cmdlets? 

Thanks!

**Comment by davidebbo** [comment]
This tracker is only for corrections on my blog posts. Please use the NuGet repo's issue tracker for general NuGet questions (I haven't been involved with NuGet in many years).
