### ISSUE TITLE
hi David. long time ago you published article named "Turning an .ascx User Control into a Redistributable Custom Control". it is a great article. respect to you sir. do you know if it is possible to the the same with VS 2017? I tried byt I keep getting error "Unknown server tag 'myPrefix:TestControl'" in my consumer app. please help.

### ISSUE THREAD

**Issue by hepekusername** [davidebbo/davidebbo.github.io#74]
Please note that this issue tracker is only used to discuss issues with the blog content, e.g.

- RSS feed is not working
- Some UI issue
- Some typos in some of the article
- etc...

For issues relating to other projects, please use the issue in the relevant repo, StackOverflow, MSDN Forum, ...

The reason I want to avoid having technical discussions here is that no one else will find them here, and I prefer having them is a real open forum.

Thanks for reading my blog!

**Comment by davidebbo** [comment]
Sorry, I have been away from the WebForms world for many years, so I have no idea how things may have changed. I would suggest asking on the ASP.NET forum, as someone there may be able to help better.

**Comment by hepekusername** [comment]
thank you
