### ISSUE TITLE
RazorGenerator needs a new release

### ISSUE THREAD

**Issue by Jehoel** [davidebbo/davidebbo.github.io#76]
Hi David,

The RazorGenerator project on GitHub hasn't seen a release since February 2017, there's also a number of pending Pull Requests.

I imagine you're probably busy to handle this yourself, I'd be happy to step-in if you'd like to add me as a collaborator to the GitHub repo to handle the PRs and Testing and give you commit to build, sign and public yourself.

**Comment by davidebbo** [comment]
@Jehoel I'm no longer involved with that project, as I don't use it myself and just don't have the cycles. Not sure if @pranavkm is still involved. Maybe the project needs some new core contributors that are better able to take care of it.

**Comment by Jehoel** [comment]
Ah, my apologies - I didn't realise you weren't listed as a maintainer anymore.
