### ISSUE TITLE
If you can Teaching us Debugging Skills Please

### ISSUE THREAD

**Issue by freesix** [davidebbo/davidebbo.github.io#79]
Hi David Ebbo, I came accross your prestigious name thru David Fowler who is Software Architect at MSFT. (https://www.youtube.com/watch?v=8akvvwQoGjs)

He let us know that he learnt a lot on Debugging from you, and personnally I'm a software developer and just started 3 years ago but after analyzing my productivity, I discover that I'm taking more time debugging a small thing/method than even writing it... I can take more than 4 hours trying to debug a single line. Also out there, there's no books teaching debugging skills. I searched google for a week and couldn't find one.

Can you pleas Sir wrote even a Book or even a blog every week regarding debugging skills / How to effectivelly debug... please to help Junior Programmer like us.

**Comment by davidebbo** [comment]
Hi freesix,

Thanks for reaching out. At this point, I no longer write much code, so I'm rather rusty on debugging, and far from an authority on the topic. But I'm sure there is a ton of good material out there for you to learn from!

Wishing you best.

**Comment by freesix** [comment]
Thank you Sir.
At least you write less code than much code you used to write.
Don't need to write codes or book to explain us how to debug... even a page blog explaning theoretically how to effectively analyze and look for a problem. That's all we want me and my friends.
