### ISSUE TITLE
The term 'nuget' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by ponmani** [davidebbo/davidebbo.github.io#8]
I try to create nuget package the following your precedures. I got the error is 
The term 'nuget' is not recognized as the name of a cmdlet, function, script file, or operable program. Please help me.

**Comment by tonytomk** [comment]
[Check it here ](https://coder-juggernaut.blogspot.in/2017/02/the-term-nuget-is-not-recognized-as.html)
