### ISSUE TITLE
Please provide copyright information for web-activator version 2.0.6

### ISSUE THREAD

**Issue by GoekhanYilmaz** [davidebbo/davidebbo.github.io#80]
Dear Madame, dear Sir,

As AvePoint Inc. we consider to use your open source software component “Web-activator version 2.0.6”

Please find related links here:
https://github.com/davidebbo/WebActivator/

https://raw.githubusercontent.com/davidebbo/WebActivator/7865ee0f69b8a7118548162e5a92c1202d1ca8fc/LICENSE.txt

In recognition of your work and the respective legal regulations we i.a. have to provide a valid copyright statement of the component. Unfortunately we could not find such copyright statement – neither in the released software package nor on the project’s webpage or in other sources.

Therefore, we kindly ask you to provide us with the valid copyright statement of the software component, so that we can comply with the license regulations.
 
If you are not the copyright holder of this software component, please let us know.

Best regards,

Gökhan YILMAZ
Senior Account Executive
Microsoft P-SSP
P: +49 89 2190989-63 | M: +49 151 25367068 | F: +49 89 2190989-99 
goekhan.yilmaz@avepoint.com | www.avepoint.com
Follow AvePoint on Facebook, Twitter and LinkedIn! 

AvePoint Deutschland GmbH | Nymphenburger Str. 3 | 80335 München
Geschäftsführer: Dr. Tianyi Jiang | Amtsgericht München | HRB 177338

**Comment by davidebbo** [comment]
Please use the issue tracker on https://github.com/davidebbo/WebActivator for all discussions related to WebActivator.

But the answer here is that you can use WebActivator in accordance to the Apache 2 license (https://github.com/davidebbo/WebActivator/blob/master/LICENSE.txt).
