### ISSUE TITLE
Invoke ARMClient with Powershell for LogAnalytics

### ISSUE THREAD

**Issue by vengateshk** [davidebbo/davidebbo.github.io#82]
$Subscription = "xxxxx"
$ResourceGroupName = "xxxx"
$LogAnalyticsName = "xxxx"
.\ARMClient.exe GET /subscriptions/$Subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.OperationalInsights/workspaces/$LogAnalyticsName/Tables?api-version=2017-04-26-preview

I would like to get the Log Analytics Workspace retention for every datatype using powershell and found that your article useful but not able to modify and use it.. any help would be useful... Thanks!

Even If we get it directly using Powershell command ?
I found the below article but no direct PS Cmdlet to get the retention for datatype
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-cost-storage#retention-by-data-type

**Comment by davidebbo** [comment]
Please ask such questions on the relevant repos. I am no longer involved with this project.
