### ISSUE TITLE
Razor Generator Question

### ISSUE THREAD

**Issue by nckabob** [davidebbo/davidebbo.github.io#84]
Hello, 

Hope all is well your way. 

I have recently updated to Visual Studio 22 and I was wondering if there are any plans to make the Razor Generator extension compatible with the latest version of visual studio.

Thanks
-Nick

**Comment by davidebbo** [comment]
I'm no longer really active on this project, but please see https://github.com/RazorGenerator/RazorGenerator/issues/225 for the latest discussion on this topic.

**Comment by Daddoon** [comment]
Just for info, as there is no answer from Jelohel, like some other author on other plugins, i did publish a forked version of RazorGenerator, available here: https://marketplace.visualstudio.com/items?itemName=GuillaumeZahra.razorgenerator2022

**Comment by nckabob** [comment]
Thanks @Daddoon !

**Comment by davidebbo** [comment]
If Jelohel disappears, you might just have to be the new maintainer! :) I wish I could help, but I've been super disconnected from the .net world since I joined Google, and I don't even have a machine with the latest VS. Though I do miss it!
