### ISSUE TITLE
Azure Function Sandbox Architecture

### ISSUE THREAD

**Issue by RBVieira** [davidebbo/davidebbo.github.io#86]
Hi, David. 

Man.. Could you help me? I really would like to understand the azure functions sandbox architecture. Do you have a drawing to share? I was trying to understand how it works when I deploy a azure function inside a docker linux. This docker is pushed inside the Sandbox? How it works?

I have made many searches but did not find just one simple drawing explaining that.

Thank you very much.

Please note that this issue tracker is only used to discuss issues with the blog content, e.g.

- RSS feed is not working
- Some UI issue
- Some typos in some of the article
- etc...

For issues relating to other projects, please use the issue in the relevant repo, StackOverflow, MSDN Forum, ...

The reason I want to avoid having technical discussions here is that no one else will find them here, and I prefer having them is a real open forum.

Thanks for reading my blog!

**Comment by davidebbo** [comment]
Please see the message about the purpose of this issue tracker. You should instead use StackOverflow or other forums for this type of questions. Also, I have not worked on Functions in 3+ years. Thanks.
