### ISSUE TITLE
Git Deployment to Azure

### ISSUE THREAD

**Issue by lili9000** [davidebbo/davidebbo.github.io#87]
Tried to use git to deploy PHP web application.  Found some old files remained at wwwroot while the old files were removed in repository after a new deployment.  Any idea why the repo and wwwroot were not synchronized?  Should I use .deployment file to add the ClearOutputPath parameter to clean up the wwwroot?

[config]
command = deploy.cmd
ClearOutputPath = true

**Comment by davidebbo** [comment]
Please open an issue on https://github.com/projectkudu/kudu/issues instead, thanks. I'm no longer involved with this project.
