### ISSUE TITLE
WAWSDeploy - Unable to prevent removing old files

### ISSUE THREAD

**Issue by alessioGit83** [davidebbo/davidebbo.github.io#88]
Hello,
I'm trying to use the tool to deploy code into Azure App Service.
The deploy process works but even if I not declare the /d parameter, the deploy process remove all old files not present in the new deployment.

Any suggestions?

Thanks
Alessio

**Comment by davidebbo** [comment]
Hi,

It is best to open an issue in the https://github.com/davidebbo/WAWSDeploy/ repo for this type of questions. But please do note that this tool has not been updated in many years, so support may be limited.
